package mif.vu.lt.psktp1.mybatis.dao;

import java.util.List;
import mif.vu.lt.psktp1.mybatis.model.AuthorsBooks;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AuthorsBooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHORS_BOOKS
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    int insert(AuthorsBooks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTHORS_BOOKS
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    List<AuthorsBooks> selectAll();

    int getResultCountByAuthorAndBookId(@Param("authorId") Integer authorId, @Param("bookId") Integer bookId);
}