package mif.vu.lt.psktp1.mybatis.dao;

import java.util.List;
import mif.vu.lt.psktp1.mybatis.model.BooksLibrary;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BooksLibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKS_LIBRARY
     *
     * @mbg.generated Wed May 11 13:09:26 EEST 2022
     */
    int insert(BooksLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKS_LIBRARY
     *
     * @mbg.generated Wed May 11 13:09:26 EEST 2022
     */
    List<BooksLibrary> selectAll();

    int getResultCountByBookAndLibraryId(@Param("bookId") Long bookId, @Param("libraryId") Long libraryId);
}