package mif.vu.lt.psktp1.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.AUTHOR_NAME
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private String authorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.AUTHOR_NAME
     *
     * @return the value of PUBLIC.AUTHOR.AUTHOR_NAME
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.AUTHOR_NAME
     *
     * @param authorName the value for PUBLIC.AUTHOR.AUTHOR_NAME
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public Integer seriesId;

    public List<Book> books;
}