package mif.vu.lt.psktp1.mybatis.model;

public class AuthorsBooks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private Integer bookListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private Integer authorListId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @return the value of PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public Integer getBookListId() {
        return bookListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @param bookListId the value for PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setBookListId(Integer bookListId) {
        this.bookListId = bookListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @return the value of PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public Integer getAuthorListId() {
        return authorListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @param authorListId the value for PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setAuthorListId(Integer authorListId) {
        this.authorListId = authorListId;
    }
}