package mif.vu.lt.psktp1.mybatis.model;

public class AuthorsBooks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private Integer booklistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private Integer authorlistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @return the value of PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public Integer getBooklistId() {
        return booklistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @param booklistId the value for PUBLIC.AUTHORS_BOOKS.BOOKLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setBooklistId(Integer booklistId) {
        this.booklistId = booklistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @return the value of PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public Integer getAuthorlistId() {
        return authorlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @param authorlistId the value for PUBLIC.AUTHORS_BOOKS.AUTHORLIST_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setAuthorlistId(Integer authorlistId) {
        this.authorlistId = authorlistId;
    }
}