package mif.vu.lt.psktp1.mybatis.model;

public class BooksLibrary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKS_LIBRARY.LIBRARY_ID
     *
     * @mbg.generated Wed May 11 13:09:26 EEST 2022
     */
    private Long libraryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKS_LIBRARY.BOOK_ID
     *
     * @mbg.generated Wed May 11 13:09:26 EEST 2022
     */
    private Long bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKS_LIBRARY.LIBRARY_ID
     *
     * @return the value of PUBLIC.BOOKS_LIBRARY.LIBRARY_ID
     *
     * @mbg.generated Wed May 11 13:09:26 EEST 2022
     */
    public Long getLibraryId() {
        return libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKS_LIBRARY.LIBRARY_ID
     *
     * @param libraryId the value for PUBLIC.BOOKS_LIBRARY.LIBRARY_ID
     *
     * @mbg.generated Wed May 11 13:09:26 EEST 2022
     */
    public void setLibraryId(Long libraryId) {
        this.libraryId = libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKS_LIBRARY.BOOK_ID
     *
     * @return the value of PUBLIC.BOOKS_LIBRARY.BOOK_ID
     *
     * @mbg.generated Wed May 11 13:09:26 EEST 2022
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKS_LIBRARY.BOOK_ID
     *
     * @param bookId the value for PUBLIC.BOOKS_LIBRARY.BOOK_ID
     *
     * @mbg.generated Wed May 11 13:09:26 EEST 2022
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }
}