package mif.vu.lt.psktp1.mybatis.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.AUTHOR
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private Integer author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.BOOK_NAME
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.SERIES_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    private Integer seriesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.ID
     *
     * @return the value of PUBLIC.BOOK.ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.ID
     *
     * @param id the value for PUBLIC.BOOK.ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.AUTHOR
     *
     * @return the value of PUBLIC.BOOK.AUTHOR
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.AUTHOR
     *
     * @param author the value for PUBLIC.BOOK.AUTHOR
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.BOOK_NAME
     *
     * @return the value of PUBLIC.BOOK.BOOK_NAME
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.BOOK_NAME
     *
     * @param bookName the value for PUBLIC.BOOK.BOOK_NAME
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.SERIES_ID
     *
     * @return the value of PUBLIC.BOOK.SERIES_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public Integer getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.SERIES_ID
     *
     * @param seriesId the value for PUBLIC.BOOK.SERIES_ID
     *
     * @mbg.generated Tue May 10 01:14:53 EEST 2022
     */
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }
}