package mif.vu.lt.psktp1.mybatis.model;

import java.util.List;
import mif.vu.lt.psktp1.entities.Author;
import mif.vu.lt.psktp1.entities.Book;

public class Series {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERIES.ID
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERIES.BOOKS_AMOUNT
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    private Integer booksAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERIES.SERIES_AUTHOR
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    private String seriesAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERIES.SERIES_NAME
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    private String seriesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SERIES.AUTHOR_ID
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    private Integer authorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERIES.ID
     *
     * @return the value of PUBLIC.SERIES.ID
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERIES.ID
     *
     * @param id the value for PUBLIC.SERIES.ID
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERIES.BOOKS_AMOUNT
     *
     * @return the value of PUBLIC.SERIES.BOOKS_AMOUNT
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public Integer getBooksAmount() {
        return booksAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERIES.BOOKS_AMOUNT
     *
     * @param booksAmount the value for PUBLIC.SERIES.BOOKS_AMOUNT
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public void setBooksAmount(Integer booksAmount) {
        this.booksAmount = booksAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERIES.SERIES_AUTHOR
     *
     * @return the value of PUBLIC.SERIES.SERIES_AUTHOR
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public String getSeriesAuthor() {
        return seriesAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERIES.SERIES_AUTHOR
     *
     * @param seriesAuthor the value for PUBLIC.SERIES.SERIES_AUTHOR
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public void setSeriesAuthor(String seriesAuthor) {
        this.seriesAuthor = seriesAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERIES.SERIES_NAME
     *
     * @return the value of PUBLIC.SERIES.SERIES_NAME
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public String getSeriesName() {
        return seriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERIES.SERIES_NAME
     *
     * @param seriesName the value for PUBLIC.SERIES.SERIES_NAME
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SERIES.AUTHOR_ID
     *
     * @return the value of PUBLIC.SERIES.AUTHOR_ID
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SERIES.AUTHOR_ID
     *
     * @param authorId the value for PUBLIC.SERIES.AUTHOR_ID
     *
     * @mbg.generated Mon May 02 21:08:27 EEST 2022
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    // Added manually
    private Author author;
    private List<Book> bookList;

}